name: booking_time
description: Booking App

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.3
  datetime_picker_formfield: ^2.0.0
  shared_preferences: ^2.0.5
  intl: ^0.17.0
  url_launcher: ^6.0.3
  get_it: ^7.1.3
  location: ^4.1.1
  


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
     - images/

